### ISSUE TITLE
mkchain dependency to gitlab registry is broken

### ISSUE THREAD

**Issue by hai-nguyen-van** [oxheadalpha/tezos-k8s#357]
```
$ mkchain foobar
Pulling docker image registry.gitlab.com/tezos/flextesa:01e3f596-run
Traceback (most recent call last):
  File "/home/nguyen-van/.local/bin/mkchain", line 8, in <module>
    sys.exit(main())
  File "/home/nguyen-van/.local/lib/python3.8/site-packages/tqchain/mkchain.py", line 198, in main
    pull_docker_images(images)
  File "/home/nguyen-van/.local/lib/python3.8/site-packages/tqchain/mkchain.py", line 144, in pull_docker_images
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker pull registry.gitlab.com/tezos/flextesa:01e3f596-run' returned non-zero exit status 1
```

**Comment by harryttd** [comment]
flextesa is now no longer a dependency
